### ISSUE TITLE
Strange errors installing Omada in Proxmox 7.2-7 Ubuntu 20.04 container

### ISSUE THREAD

**Issue by emanuelebruno** [monsn0/omada-installer#2]
Hi, after I have create an Ubuntu container with 1GB Ram+1GB Swap+8GB disk, etc. and after I have installed some updates, I tryed to install using your script... I have attached the error that I have met
```
apt update && apt upgrade -y
apt install curl
cd /root
curl -s https://raw.githubusercontent.com/monsn0/omada-installer/main/install-omada-controller.sh | sudo bash
```
![image](https://user-images.githubusercontent.com/16278010/182440347-d6bae112-b0ac-4954-b49a-c023a2bb5606.png)

**Comment by monsn0** [comment]
It appears you are missing the 'gnupg' package which is needed to add the gpg key for the mongodb repo.
Please try installing it and re running the script.

`apt-get install gnupg`

This package comes with Ubuntu 20.04 but I can add it to the script to ensure its installed prior to proceeding.
